In [1]:
import pandas as pd
import numpy as np
import os
sys.path.append(os.path.abspath('..'))
import matplotlib.pyplot as plt

In [2]:
dfLinear = pd.read_csv('../data/linear.csv')
dfLogistic = pd.read_csv('../data/logistic.csv')

x1 = dfLinear['ps']
y1 = dfLinear['fs']

x2 = dfLogistic['value']
y2 = dfLogistic['status']

print(dfLinear)
print("\n", dfLogistic)

    ps  fs
0   90  93
1   87  88
2  100  98
3   78  78
4   75  76
5   74  76
6   70  69
7   50  60
8   20  10

    value  status
0     90       1
1     87       1
2    100       1
3     78       1
4     75       1
5     74       0
6     70       0
7     50       0
8     20       0


In [4]:
%load_ext autoreload
%autoreload 2
from models.Regression import *

modelLin = LinearRegression(x=x1, y=y1)
weightLin, biasLin = modelLin.fit(lr=0.0001, epoch=1000)

weightLin = weightLin
biasLin = biasLin

print(f"Weight:\n{weightLin}")
print(f"Bias:\n{biasLin}")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Weight:
1.0129322322868863
Bias:
-0.07005637948625604


In [5]:
input = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
for n in input:
    ypred = round(modelLin.predict(n), 2)
    print(f"yPred {n}:\n{ypred}")

yPred 10:
10.06
yPred 20:
20.19
yPred 30:
30.32
yPred 40:
40.45
yPred 50:
50.58
yPred 60:
60.71
yPred 70:
70.84
yPred 80:
80.96
yPred 90:
91.09
yPred 100:
101.22


In [15]:
%load_ext autoreload
%autoreload 2
from models.Regression import *

modelLog = LogisticRegression(x=x2, y=y2)
weightLog, biasLog = modelLog.fit(lr=0.001, epoch=1000)

weightLog = (weightLog)
biasLog = (biasLog)

print(f"Weight:\n{weightLog}")
print(f"Bias:\n{biasLog}")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Weight:
[[0.00543681]
 [0.00525558]
 [0.0060409 ]
 [0.0047119 ]
 [0.00453067]
 [0.00447027]
 [0.00422863]
 [0.00302045]
 [0.00120818]]
Bias:
0.006040899525538295


In [16]:
for n in input:
    ypred = modelLog.predict(n)
    np.set_printoptions(suppress=True, precision=8)
    print(f"yPred {n}:\n{ypred}")

yPred 10:
[[0.51509766]
 [0.51464499]
 [0.51660636]
 [0.51328685]
 [0.51283409]
 [0.51268317]
 [0.51207945]
 [0.50906036]
 [0.50453055]]
yPred 20:
[[0.52866281]
 [0.52775956]
 [0.53167226]
 [0.52504875]
 [0.5241448 ]
 [0.52384345]
 [0.52263789]
 [0.51660636]
 [0.50755055]]
yPred 30:
[[0.54218577]
 [0.54083593]
 [0.54668063]
 [0.53678292]
 [0.5354308 ]
 [0.53497998]
 [0.53317613]
 [0.5241448 ]
 [0.51057   ]]
yPred 40:
[[0.55564685]
 [0.55385631]
 [0.56160462]
 [0.54847649]
 [0.54668063]
 [0.54608174]
 [0.54368485]
 [0.53167226]
 [0.51358868]]
yPred 50:
[[0.56902674]
 [0.5668032 ]
 [0.57641798]
 [0.56011677]
 [0.55788298]
 [0.55713786]
 [0.55415483]
 [0.53918533]
 [0.51660636]]
yPred 60:
[[0.58230661]
 [0.57965952]
 [0.59109524]
 [0.57169131]
 [0.56902674]
 [0.56813765]
 [0.56457697]
 [0.54668063]
 [0.51962284]]
yPred 70:
[[0.59546818]
 [0.59240867]
 [0.60561189]
 [0.58318792]
 [0.58010103]
 [0.57907065]
 [0.57494235]
 [0.55415483]
 [0.52263789]]
yPred 80:
[[0.60849387]
 [0.60503461]
 [0